=== Svetizoloto/webs/blog-page.dtd
<!ELEMENT blogpage (header, header-desc, article+)>

<!ELEMENT header (#PCDATA)>
<!ELEMENT header-desc (#PCDATA)>

<!ELEMENT article (content,inf-meta,comms)>

<!ELEMENT content (theme,description)>
<!ELEMENT theme (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT inf-meta (inf,author,keyWords,apps)>
<!ELEMENT comms (comment+)>

<!ELEMENT comment (commentText,comment-author,comment-tags)>
<!ELEMENT commentText (#PCDATA)>
<!ELEMENT comment-author (#PCDATA)>
<!ELEMENT comment-tags (comment-tag+)>
<!ELEMENT comment-tag (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT keyWords (keyword+)>
<!ELEMENT apps (appfile,applink)>

<!ELEMENT keyword (#PCDATA)>
<!ELEMENT appfile (#PCDATA)>

<!ELEMENT applink (applink-name,value)>
<!ELEMENT applink-name (#PCDATA)>
<!ELEMENT value (#PCDATA)>

=== Svetizoloto/webs/blog-page.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE blogpage SYSTEM "blog-page.dtd">
<blogpage>
    <header>Accusamus</header>
    <header-desc>At vero eos et accusamus et iusto odio dignissimos</header-desc>
    <article>
        <content>
            <theme>At vero eos et accusamus et iusto odio dignissimos </theme>
            <description>
        At vero eos et accusamus et iusto odio dignissimos ducimus qui
        blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et
        quas molestias excepturi sint occaecati cupiditate non provident, similique
        sunt in culpa qui officia deserunt mollitia animi, id est laborum et 
        dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.
        Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil
        impedit quo minus id quod maxime placeat facere possimus, omnis 
        voluptas assumenda est, omnis dolor repellendus.
            </description>
        </content>

        <inf-meta>  
            <date>6 декабря 2020</date>
            <author>First_name Last_name</author>
            <keyWords>
                <keyword>Woman </keyword>
                <keyword>Footbal </keyword>
                <keyword>ManCity </keyword>
            </keyWords>
            <apps>
                <appfile>images/blog/image1.jpg</appfile>
                <applink>
                    <applink-name>Post</applink-name>
                    <value>https://ru.wikipedia.org/wiki/Common_Language_Runtime</value>
                </applink>
            </apps>
        </inf-meta>
        <comms>
            <comment>
                <commentText>Dignissimos ducimus qui blanditiis</commentText>
                <comment-author>Александр</comment-author>
                <comment-tags>
                <comment-tag>Комментарий </comment-tag>
            </comment-tags>
            </comment>
            <comment>
                <commentText>Dolores et quas molestias</commentText>
                <comment-author>Евгения</comment-author>
                <comment-tags>
            <comment-tag>Вопрос </comment-tag>
            </comment-tags>
            </comment>
            <comment>
                <commentText>Iusto odio dignissimos ducimus qui blanditiis
                 praesentium voluptatum deleniti</commentText>
                <comment-author>First_name Last_name</comment-author>
            <comment-tags>
            <comment-tag> Автор </comment-tag>
            </comment-tags>
            </comment>
        </comms>
    </article>
    <article>
        <content>
                <theme>At vero eos et accusamus et iusto odio dignissimos </theme>
                <description>
        At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis
        praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias
        excepturi sint occaecati cupiditate non provident, similique sunt in culpa
        qui officia deserunt mollitia animi, id est laborum et dolorum fuga. 
        Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore,
        cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod
        maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor
        repellendus. 
                </description>
        </content>
        <inf-meta>
            <date>6 декабря 2020</date>
            <author>First_name Last_name</author>
            <keyWords>
                <keyword>Woman </keyword>
                <keyword>Footbal </keyword>
                <keyword>ManCity </keyword>
            </keyWords>
            <apps>
                <appfile>images/blog/image1.jpg</appfile>
            <applink>
                <applink-name>Post</applink-name>
                <value>https://ru.wikipedia.org/wiki/Common_Language_Runtime</value>
            </applink>
            </apps>
        </inf-meta>
            <comms>
            <comment>
                <commentText>Dignissimos ducimus qui blanditiis</commentText>
                <comment-author>Александр</comment-author>
                <comment-tags>
                <comment-tag>Комментарий </comment-tag>
                </comment-tags>
            </comment>
            <comment>
                <commentText>Dolores et quas molestias</commentText>
                <comment-author>Евгения</comment-author>
                <comment-tags>
                <comment-tag>Вопрос </comment-tag>
                </comment-tags>
            </comment>
            <comment>
                <commentText>Iusto odio dignissimos ducimus qui blanditiis
               praesentium voluptatum deleniti</commentText>
                <comment-author>First_name Last_name</comment-author>
                <comment-tags>
                <comment-tag> Автор </comment-tag>
                </comment-tags>
            </comment>
            </comms>
    </article>
    <article>
            <content>
            <theme>At vero eos et accusamus et iusto odio dignissimos </theme>
                    <description>
            At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis
            praesentium voluptatum deleniti atque corrupti quos dolores et quas
            molestias excepturi sint occaecati cupiditate non provident, similique 
            sunt in culpa qui officia deserunt mollitia animi, id est laborum et
            dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.
            Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil
            impedit quo minus id quod maxime placeat facere possimus, omnis voluptas
            assumenda est, omnis dolor repellendus. 
                    </description>
            </content>
        <inf-meta>
            <date>6 декабря 2020</date>
            <author>First_name Last_name</author>
            <keyWords>
                <keyword>Woman </keyword>
                <keyword>Footbal </keyword>
                <keyword>ManCity </keyword>
            </keyWords>
        <apps>
        <appfile>images/blog/image1.jpg</appfile>
        <applink>
            <applink-name>Post</applink-name>
            <value>https://ru.wikipedia.org/wiki/Common_Language_Runtime</value>
        </applink>
        </apps>
        </inf-meta>
        <comms>
        <comment>
            <commentText>Dignissimos ducimus qui blanditiis</commentText>
            <comment-author>Александр</comment-author>
            <comment-tags>
            <comment-tag>Комментарий </comment-tag>
            </comment-tags>
        </comment>
        <comment>
            <commentText>Dolores et quas molestias</commentText>
            <comment-author>Евгения</comment-author>
            <comment-tags>
            <comment-tag>Вопрос </comment-tag>
            </comment-tags>
        </comment>
        <comment>
            <commentText>Iusto odio dignissimos ducimus qui blanditiis praesentium 
            voluptatum deleniti</commentText>
            <comment-author>First_name Last_name</comment-author>
            <comment-tags>
            <comment-tag> Автор </comment-tag>
            </comment-tags>
        </comment>
        </comms>
    </article>
    <article>
        <content>
        <theme>At vero eos et accusamus et iusto odio dignissimos </theme>      
                    <description>
            At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis
            praesentium voluptatum deleniti atque corrupti quos dolores et quas
            molestias excepturi sint occaecati cupiditate non provident, similique
            sunt in culpa qui officia deserunt mollitia animi, id est laborum et
            dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. 
            Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil 
            impedit quo minus id quod maxime placeat facere possimus, omnis voluptas
            assumenda est, omnis dolor repellendus. 
                    </description>
        </content>
    <inf-meta>
        <inf>6 декабря 2020</inf>
        <author>First_name Last_name</author>
         <keyWords>
            <keyword>Woman </keyword>
            <keyword>Footbal </keyword>
            <keyword>ManCity </keyword>
        </keyWords>
        <apps>
        <appfile>images/blog/image1.jpg</appfile>
        <applink>
            <applink-name>Post</applink-name>
            <value>https://ru.wikipedia.org/wiki/Common_Language_Runtime</value>
        </applink>
        </apps>
    </inf-meta>
        <comms>
        <comment>
            <commentText>Dignissimos ducimus qui blanditiis</commentText>
            <comment-author>Александр</comment-author>
            <comment-tags>
            <comment-tag>Комментарий </comment-tag>
            </comment-tags>
        </comment>
        <comment>
            <commentText>Dolores et quas molestias</commentText>
            <comment-author>Евгения</comment-author>
            <comment-tags>
            <comment-tag>Вопрос </comment-tag>
            </comment-tags>
        </comment>
        <comment>
            <commentText>Iusto odio dignissimos ducimus qui blanditiis praesentium
             voluptatum deleniti</commentText>
             <comment-author>First_name Last_name</comment-author>
             <comment-tags>
             <comment-tag> Автор </comment-tag>
             </comment-tags>
        </comment>
        </comms>
            </article>
            <article>
        <content>
    <theme>At vero eos et accusamus et iusto odio dignissimos </theme>
                    <description>
            At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis
